on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to server
      run: echo "Deploying..."
      env:
        WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        X-GitHub-Event: push

    - name: Notify deployment
      run: |
        curl -X POST -H 'X-GitHub-Event: push' $WEBHOOK_URL